version: '3'

services:
    focalboard:
      image: mattermost/focalboard:latest
      restart: always
      ports:
        - "8000:8000"
      environment:
        - FOCALBOARD_SITEURL=http://<myIp>:8000
        - FOCALBOARD_DATABASE_DRIVER=memory
